name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    env:
      PYTEST_ADDOPTS: "--cov --cov-report=xml"

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.6
            aiohttp-version: aiohttp30
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp31
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp32
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp33
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp34
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp35
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp36
            os: ubuntu-18.04
          - python-version: 3.6
            aiohttp-version: aiohttp37
            os: ubuntu-18.04

          - python-version: 3.7
            aiohttp-version: aiohttp33
            os: ubuntu-latest
          - python-version: 3.7
            aiohttp-version: aiohttp34
            os: ubuntu-latest
          - python-version: 3.7
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-version: 3.7
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-version: 3.7
            aiohttp-version: aiohttp37
            os: ubuntu-latest

          - python-version: 3.8
            aiohttp-version: aiohttp33
            os: ubuntu-latest
          - python-version: 3.8
            aiohttp-version: aiohttp34
            os: ubuntu-latest
          - python-version: 3.8
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-version: 3.8
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-version: 3.8
            aiohttp-version: aiohttp37
            os: ubuntu-latest

          - python-version: 3.9
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-version: 3.9
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-version: 3.9
            aiohttp-version: aiohttp37
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tests
      run: |
        tox -e py${{ matrix.python-version }}-${{ matrix.aiohttp-version }}
    - uses: codecov/codecov-action@v2
      with:
        file: coverage.xml